PSI_DUCK/urls.py
from django.urls import path

from .views import *
# Autori: Nikola Milosavljevic 0355/2021
#         Aleksandar Vuckovic  0733/2022
#         Vuk Davidovic        0705/2018
#         Mihajlo Milojevic    0317/2021


# kada dodajete u HTML, koristite "name"
# pr. href="{% url 'register' %}"
urlpatterns = [
     path('', index, name='home'),
     path('cart', cart_req, name='cart'),
     path('addcard', addcard_req, name='addcard'),
     path('deletecard<int:karta_id>', deletecard_req, name='delete_card'),
     path('confirm_delete/<int:karta_id>/', confirm_delete, name='confirm_delete'),
     path('card_details<int:karta_id>', card_details_req, name='card_details'),
     path('card_noadmin', card_noadmin_req, name='card_noadmin'),
     path('card_noregister', card_noregister_req, name='card_noregister'),
     path('checkout', checkout_req, name='checkout'),
     path('logout', logout_req, name='logout'),
     path('login', login_req, name='login'),
     path('popular', popular_req, name='popular'),
     path('purchase_history', purchase_history_req, name='purchase_history'),
     path('register', register_req, name='register'),
     path('wishlist', wishlist_req, name='wishlist'),
     path('add_to_wishlist/<int:karta_id>/', add_to_wishlist, name='add_to_wishlist'),
     path('remove_from_wishlist/<int:karta_id>/', remove_from_wishlist, name='remove_from_wishlist'),
     path('fetch_cards', fetch_cards, name='fetch_cards'),
     path('update_card_price<int:karta_id>', update_card_price, name='update_card_price'),
     path('update_card_discount<int:karta_id>', update_card_discount, name='update_card_discount'),
     path('increment_karta/<int:karta_id>/', increment_karta, name='increment_karta'),
     path('decrement_karta/<int:karta_id>/', decrement_karta, name='decrement_karta'),
     path('add_to_cart/<int:karta_id>/', add_to_cart, name='add_to_cart'),
     path('remove_from_cart/<int:karta_id>/', remove_from_cart, name='remove_from_cart'),
     path('like_card<int:karta_id>/', like_card, name='like_card'),
     path('dislike_card<int:karta_id>/', dislike_card, name='dislike_card'),
]

#python.exe ./manage.py runserver ->ZA RUNOVANJE PYTHON APLIKACIJE

PSI_DUCK/models.py
import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.utils import timezone
# Create your models here.
# Autori: Nikola Milosavljevic 0355/2021
#         Vuk Davidovic        0705/2018

class RegistrovanKorisnik(AbstractUser):
    """
        All registered users
        :model: RegistrovanKorisnik
    """
    slika = models.ImageField(upload_to='imgs/', null=True, verbose_name='Profile picture')

    class Meta:
        db_table = 'RegistrovanKorisnik'

class Karta(models.Model):
    """
            Stores the information about karta
            :model: Karta
        """
    naziv = models.CharField(max_length=20)
    cena = models.FloatField(validators=[MinValueValidator(0)]) #ovo osigurava da ne moze da se unese negativna cena
    opis = models.CharField(max_length=255) #blank=True znaci da je neobavezno polje, cisto radi probe
    brPrimeraka = models.IntegerField(validators=[MinValueValidator(0)],default=1)
    brLajkova = models.IntegerField(validators=[MinValueValidator(0)],default=0)
    brDislajkova = models.IntegerField(validators=[MinValueValidator(0)],default=0)
    slika = models.ImageField(upload_to="imgs/", null=True, verbose_name='Pokemon picture')
    popust = models.IntegerField(validators=[MinValueValidator(0)],default=0)

    """
        Returns the price with the discount
    """
    def cena_sa_popustom(self):
        return self.cena * (1 - self.popust /100)
    class Meta:
        db_table = 'Karta'


class IstorijaKupovine(models.Model):
    """
                Stores the information purchase history
                :model: IstorijaKupovine
            """
    korisnik = models.ForeignKey(RegistrovanKorisnik, on_delete=models.CASCADE)
    karta = models.ForeignKey(Karta, on_delete=models.CASCADE)
    kolicina = models.IntegerField(default=0)
    datum = models.DateField(default=timezone.now)
    vreme = models.TimeField(default=timezone.now)

    class Meta:
        db_table = 'IstorijaKupovine'

class InformacijePorudzbine(models.Model):
    """
                Stores the information about purchase information
                :model: InformacijePorudzbine
            """
    datum = models.DateField(default=timezone.now)
    vreme = models.TimeField(default=timezone.now)
    #varijacija:
    #datum = models.DateTimeField(default=datetime.datetime.now());
    ime = models.CharField(max_length=20)
    prezime = models.CharField(max_length=20)
    adresa = models.CharField(max_length=100)
    grad = models.CharField(max_length=20)
    drzava = models.CharField(max_length=20)
    korisnik = models.ForeignKey(RegistrovanKorisnik, on_delete=models.CASCADE)
    class Meta:
        db_table = 'InformacijePorudzbine'

class Korpa(models.Model):
    """
                Stores the information about the cart
                :model: Korpa
            """
    porudzbina = models.ForeignKey(InformacijePorudzbine, on_delete=models.CASCADE)
    karta = models.ForeignKey(Karta, on_delete=models.CASCADE)
    brojArtikala = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    class Meta:
        unique_together = ('porudzbina', 'karta')
        db_table = 'Korpa'

class ListaZelja(models.Model):
    """
                Stores the information about the wishlist
                :model: ListaZelja
            """
    karta = models.ForeignKey(Karta, on_delete=models.CASCADE)
    korisnik = models.ForeignKey(RegistrovanKorisnik, on_delete=models.CASCADE)
    class Meta:
        # za definisanje toga da na zajednickom nivou moraju da budu unique
        unique_together = ('karta', 'korisnik')
        db_table = 'ListaZelja'

class jeOcenio(models.Model):
    """
                Stores information about the user rating the card
                Related to :model: registrovanKorisnik and :model: karta
                :model: jeOcenio
            """
    MOGUCE_OCENE = [
        (-1, '-1'),
        (0, '0'),
        (1, '1'),
    ]

    karta = models.ForeignKey(Karta, on_delete=models.CASCADE)
    korisnik = models.ForeignKey(RegistrovanKorisnik, on_delete=models.CASCADE)
    ocena = models.IntegerField(choices=MOGUCE_OCENE, default=0)
    class Meta:
        unique_together = ('karta', 'korisnik')
        db_table = 'jeOcenio'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=0.5 " />
  <title>PokeShop</title>
  <!-- Bootstrap CSS -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/logo.png' %}" >

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <style>
    /* Custom CSS */
    .cart-popup {
      position: fixed;
      bottom: 20px;
      right: 20px;
      background-color: #fff;
      border: 1px solid #ccc;
      padding: 10px;
      border-radius: 5px;
      box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
      display: none; /* Hidden by default */
      z-index: 999; /* Ensure it appears on top of other content */
    }
  </style>
</head>
<header style="background-color: aquamarine; text-align: center">
    {% block header %}
        {% if messages %}
            {% for msg in messages %}
                {{ msg }}
            {% endfor %}
            <br>
        {% endif %}


{#        autenticate  vraca user-a#}
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">logout</a>
            	   {{ user}}
        {% else %}
            <a href="{% url 'login' %}">login</a>
        {% endif %}

    {% endblock %}

</header>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}" >
    <img src="{% static 'img/logo.png' %}" class="navbar-icon" alt="Logo" style="width: 8%;"> <!-- Icon added beside the logo -->
    PokemonShop
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'wishlist' %}">Wishlist</a>
          <a class="dropdown-item" href="{% url 'purchase_history' %}">Purchase History</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}

{% endblock %}


<!-- Bootstrap JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
<footer style=" bottom: 0; text-align: center; background: deepskyblue; width: 100%; left: 0">
    Copyright PSI-duck Company
</footer>
</html> 

templates/card_details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
  <!-- Card Details -->
<div class="row">

</div>
  <div class="card-details-container">
      <br>
  <div class="row">
      <div class="col-md-4 mb-4">
{#    Ubacivanje drugog .html-a u ovaj kao deo njega      #}
      {% include 'card_info.html' %}
{#          #}
          {% if perms.PSI_DUCK.change_karta %}

              <form method="post" action="{% url 'confirm_delete' karta.id %}">
                            {% csrf_token %}
                        <br>
                            <button type="submit" name="delete_this_card" class="btn btn-danger">Delete this card</button>
                        </form>
              {% endif %}
      {% if perms.PSI_DUCK.change_karta %}

              <form method="post" action="{% url 'increment_karta' karta.id %}">
                            {% csrf_token %}
                        <br>
                            <button type="submit" name="add_another_instance" class="btn btn-dark">Add another instance</button>
                        </form>
              {% endif %}
       {% if perms.PSI_DUCK.change_karta %}

              <form method="post" action="{% url 'decrement_karta' karta.id %}">
                            {% csrf_token %}
                        <br>
                            <button type="submit" name="delete_one_instance" class="btn btn-danger card-count-button">Delete one instance</button>
                        </form>
              {% endif %}

  </div>
  <div class="col-md-2"></div>
  <div class="col-md-4 mb-4">
{#   TO_DO #}
        {% if perms.PSI_DUCK.change_karta %}


            <form method="post" action="{% url 'update_card_price' karta.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="new_price">New price ($):</label>
                        <input type="number" class="form-control" id="new_price" name="new_price" min="0" value="0" style="width: 100%;" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Save price</button>
                </form>

                <br>

                <form method="post" action="{% url 'update_card_discount' karta.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="new_discount">New Discount (%):</label>
                        <input type="number" class="form-control" id="new_discount" name="new_discount" min="0" max="100" value="0" style="width: 100%;" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Save discount</button>
                </form>


    {% endif %}
      <br>
   {% if perms.PSI_DUCK.add_korpa and karta.brPrimeraka > 0%}

       <form method="post" action="{% url 'add_to_cart' karta.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Add to cart</button>
       </form>

    {% endif %}
  </div>

  </div>


      <br><br>
{#      <div class="row">#}
{#        <div class="col-sm-12">#}
{#            <button type="button" class="btn btn-success">Dodaj u magacin</button>#}
{#        </div>#}
{#      </div>#}
{#      <br>#}
{#      <div class="row">#}
{#        <div class="col-sm-12">#}
{#            <button type="button" class="btn btn-danger">Izbaci iz magacina</button>#}
{#        </div>#}
{#      </div>#}
    </div>
  </div>



{% endblock %}

templates/card_info.html
{% load static %}
<div class="card-container">

  <div class="card position-relative">
    <img src="{{ slikaUrl }}" class="card-img-top {% if karta.brPrimeraka == 0 %}grayscale{% endif %}" alt="...">
    <div class="card-body">
      <h5 class="card-title" style="font-size: x-large;">{{ karta.naziv }}</h5>
      <p class="card-text">Description: {{ karta.opis }}</p>
      <p class="card-text">Price: ${{ karta.cena }}</p>
      <p class="card-text">Discount: {{ karta.popust }}%</p>
      <p class="card-text">Price with discount: ${{ karta.cena_sa_popustom }}</p>
    </div>
  </div>
<div class="card-info bg-info text-white p-2 d-flex justify-content-between align-items-center">
    <span>Number of cards:</span>
    <button class="btn btn-warning" name="num_of_cards" style="pointer-events: none;">
      {{ karta.brPrimeraka }}
    </button>
  </div>
</div>
<style>
  .grayscale {
    filter: grayscale(100%);
  }
  .card-container {
    margin-bottom: 1rem;
  }
  .card-info {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #17a2b8; /* Bootstrap info background color */
    color: white;
    padding: 0.5rem;
  }
  .btn-light {
    background-color: #f8f9fa; /* Bootstrap light button background color */
    color: #000;
  }
</style>

templates/card_noadmin.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
    <!-- Card Details -->
    <div class="card-details-container">
      <div class="card-img-container">
        <img src="primer slike/SWSH4_EN_83.png" class="card-img-top" alt="..." style="height: 500px;">
      </div>
      <div class="card-info">
        <h3>Wooper</h3>
        <p>Blatnjavi smesni vodeni lol</p>
        <div class="row">
          <div class="col-sm-12">
              <button type="button" class="btn btn-success">Dodaj u korpu</button>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/card_noregister.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
  <!-- Card Details -->
  <div class="card-details-container">
    <div class="card-img-container">
      <img src="primer slike\XY1_EN_42.png" class="card-img-top" alt="..." style="height: 500px;">
    </div>
    <div class="card-info">
      <h3>Pikachu</h3>
      <p> pika pika chubzzzzzzzzzzzzzzzZZZZZZZZZZZZZZZZZZZZZZ</p>
    </div>
  </div>
</div>

{% endblock %}

templates/cards_partial.html
{% for karta in karte %}
  <div class="col-md-4 mb-4">
    <div class="card" id="karta{{ karta.id }}">
      <a href="{% url 'card_details' karta.id %}">
        <img src="{{ karta.slika.url }}" class="card-img-top {% if karta.brPrimeraka == 0 %}grayscale{% endif %}" alt="...">
        <div class="card-body">
          <h5 class="card-title" style="font-size: x-large;">{{ karta.naziv }}</h5>
        </div>
      </a>

      <p class="card-text description">Description : {{ karta.opis }}</p>
      <p class="card-text">Price : ${{ karta.cena }}</p>
      <p class="card-text">Discount : {{ karta.popust }}%</p>
      <p class="card-text">Price with discount : ${{ karta.cena_sa_popustom }}</p>

<div class="btn-group" role="group" aria-label="Card Actions" style="display: flex; width: 100%;">
    <form method="POST" action="{% url 'like_card' karta.id %}" style="flex: 0 0 25%; margin: 0;">
        {% csrf_token %}
        <button type="submit" id="like{{ karta.id }}" class="btn btn-success" style="width: 100%;">Like</button>
    </form>
    <form method="POST" action="{% url 'dislike_card' karta.id %}" style="flex: 0 0 25%; margin: 0;">
        {% csrf_token %}
        <button type="submit" id="dislike{{ karta.id }}" class="btn btn-danger" style="width: 100%;">Dislike</button>
    </form>
    <form method="POST" action="{% url 'add_to_wishlist' karta.id %}" style="flex: 0 0 50%; margin: 0;">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" id="addToWishlist{{ karta.id }}" style="width: 100%;">Add to wishlist</button>
    </form>
</div>
    </div>
  </div>
{% endfor %}

<style>
  .grayscale {
    filter: grayscale(100%);
  }

  .description {
    white-space: nowrap;        /* Prevents the text from wrapping */
    overflow: hidden;           /* Ensures the overflow content is not visible */
    text-overflow: ellipsis;    /* Adds the ellipsis ('...') */
    display: block;             /* Ensures the element is a block-level element */
    width: 100%;                /* Ensures the element takes the full width available */
  }
</style>

templates/cart.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container mt-5">
  <h1 style="text-align: center">Cart</h1>
    {% if total_items == 0 %}
    	<br>
        <h2 style="text-align:center">Your cart is empty!</h2>
    {% else %}
        <table class="table">
        <thead>
          <tr>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart_items %}
          <tr>
            <td><img src="{{ item.karta.slika.url }}" alt="{{ item.karta.naziv }}" style="width: 20%;"></td>
            <td>{{ item.karta.naziv }}</td>
            <td>${{ item.karta.cena_sa_popustom }}</td>
            <td>{{ item.brojArtikala }}</td>
            <td>${{ item.total_price }}</td>
            <td>
              <form action="{% url 'remove_from_cart' item.karta.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove</button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
        </table>
        <div class="row">
        <div class="col-md-6 offset-md-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Your Order</h5>
              <p class="card-text">Total items: {{ total_items }}</p>
              <p class="card-text">Total price: ${{ total_price }}</p>
              <a href="{% url 'checkout' %}" class="btn btn-primary">Proceed to Checkout</a>
            </div>
          </div>
        </div>
        </div>
    {% endif %}
</div>

{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<!-- Main Content -->
<div class="container mt-5">
{% if total_price == 0 %}
	<br>
    <h1 style="text-align: center">You didn't add any items to the cart!</h1>
{% else %}

  <div class="row">
    <!-- Checkout Form -->
    <div class="col-md-8">
      <h2 style="text-align: center; font-size: 35px">Payment</h2>
      <hr>
      <form method="post" action="{% url 'checkout' %}">
        {% csrf_token %}
          {% crispy form %}
          <br>
      </form>

    </div>
    <!-- Order Summary -->
    <div class="col-md-4">
      <h2>Your Order</h2>

      <div class="card">
        <div class="card-body">
          {% for item in cart_items %}
            <div class="order-item">
              <p><strong>Product Name:</strong> {{ item.karta.naziv }}</p>
              <p><strong>Quantity:</strong> {{ item.brojArtikala }}</p>
              <p><strong>Price:</strong> ${{ item.price }}</p>
            </div>
            <hr>
          {% endfor %}
          <p class="total-price"><strong>Total:</strong> ${{ total_price }}</p>
        </div>
      </div>
    </div>
  </div>
{% endif %}
</div>
<style>
  .order-summary {
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 10px;
  }
  .order-item {
    margin-bottom: 15px;
  }
  .order-item p {
    margin: 0;
  }
  .total-price {
    font-size: 1.2em;
    text-align: center;
  }
  hr {
    border-top: 5px solid #dee2e6;
  }
  legend{
      font-style: italic;
  }
</style>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
<div class="row">
    <div class="col-md-12 mb-3">
      <div class="form-group">
        <label for="sorting" style="color: black; font-size:x-large ;">Sort by:</label>
        <select class="form-control" id="sorting" style="width: 25%;">
          <option value="nameasc" selected>Name (nameasc)</option>
          <option value="namedesc" >Name (namedesc)</option>
          <option value="priceasc" >Price (priceasc)</option>
          <option value="pricedesc">Price (pricedesc)</option>
        </select>
      </div>
    </div>
  </div>
  <div class="row" id="cards-container">
      
      
      
    {% include 'cards_partial.html' %}
      
      
  </div>
  <!-- Button for Most Popular Cards -->
  <div class="row">
    <div class="col-md-12 text-center">
           <a href="{% url 'popular' %}" name="mostPopular" class="btn btn-lg" style="background-color: orange; color: white; border: 2px solid white;">Most popular cards!</a>
    </div>
    {% if perms.PSI_DUCK.add_karta %}
    	<div class="col-md-12 text-center mt-3">
             <a href="{% url 'addcard' %}" class="btn btn-lg btn-success">Add new card</a>
        </div>
    {% endif %}
{#        How  TO SEEE PERMISIONS    #}
        {#<ul>#}
        {#{% for perm in user.get_all_permissions %}#}
        {#    <li>{{ perm }}</li>#}
        {#{% endfor %}#}
        {#</ul>#}
    {% if perms.PSI_DUCK.add_korpa %}
          <a href="{% url 'cart' %}" class="btn btn-primary">View cart
              <div class="shopping-cart">
                <div class="cart-items">{{ cart_items_count }}</div>
                <img src="https://img.icons8.com/ios/50/000000/shopping-cart.png"/>
              </div>
          </a>
    {% endif %}
  </div>
</div>

{#    Ovo cudo je tu radi sortiranja karata i pamcenja sorta u LocalStorage da bi kada #}
{#    se korisnik vrati opet mogao isti sort da mu se pokaze#}
<script>
  function fetchCards(sort_by = null) {
         if (!sort_by) {
              sort_by = document.getElementById('sorting').value;
            }
         fetch(`{% url 'fetch_cards' %}?sort_by=${sort_by}`)
        .then(response => response.json())
        .then(data => {
            document.getElementById('cards-container').innerHTML = data['html'];
        })
        .catch(error => {
            console.error('Error fetching cards:', error);
        });
}

document.addEventListener('DOMContentLoaded', function() {
    // Set the sorting option from local storage
    const savedSortOption = localStorage.getItem('sort_by');
    if (savedSortOption) {
      document.getElementById('sorting').value = savedSortOption;
    }

    fetchCards(savedSortOption)
    // Fetch cards every second

    // Fetch cards on sorting change
    document.getElementById('sorting').addEventListener('change', function(event) {
      const selectedSortOption = event.target.value;
      localStorage.setItem('sort_by', selectedSortOption);
      fetchCards(selectedSortOption);
    });

    setInterval(fetchCards, 5000);

});

</script>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">Login</h2>
{#        Crispy , gora sam load crispy, a dole stavio gde treba #}
        <form  method="post">
        {% csrf_token %}
            {% crispy form %}
        </form>

     <br>
      <!-- Register Link -->
      <div class="mt-3">
        <p>Don't have account? <a href="{% url 'register' %}">Register here</a></p>
      </div>
    </div>
  </div>
</div>
{##}
<script src="{% static 'script/logiN.js' %}"></script>



{% endblock %}

templates/popular.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<div class="container mt-5">

  <div class="row" id="cards-container">
      
    {% include 'cards_partial.html' %}
      
      
  </div>
  <div class="row">
    {% if perms.PSI_DUCK.view_karta %}
          <a href="{% url 'cart' %}" class="btn btn-primary">View cart
              <div class="shopping-cart">
                <div class="cart-items">{{ cart_items_count }}</div>
                <img src="https://img.icons8.com/ios/50/000000/shopping-cart.png"/>
              </div>
          </a>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/purchase_history.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Main Content -->
<div class="container mt-5">
  <h2>Purchase History</h2>
  <!-- Purchase History Table -->
  <table class="table table-dark table-striped text-center table-hover">
    <thead>
      <tr>
        <th scope="col">Image</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Date</th>
        <th scope="col">Time</th>
        <th scope="col">Total Price</th>
      </tr>
    </thead>
    <tbody>
      {% for entry in purchase_history%}
      <tr>
        <td><img src="{{ entry.karta.slika.url }}" alt="Card Image" style="width: 20%;"></td>
        <td>{{ entry.karta.naziv }}</td>
        <td>${{ entry.karta.cena_sa_popustom }}</td>
        <td>{{ entry.kolicina }}</td>
        <td>{{ entry.datum }}</td>
        <td>{{ entry.vreme }}</td>
        <td>${{ entry.total_price }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}